;Program: LED blink
LED EQU P1.0
ORG 00H
BLINK:
	SETB LED	;LED OFF
	ACALL DELAY
	CLR LED	;LED ON
	ACALL DELAY
	AJMP BLINK
	
DELAY:	;Function for delay
		MOV R0, #10
LOOP2:	MOV R1, #200
LOOP1:	MOV R2, #200
LOOP:	DJNZ R2, LOOP
		DJNZ R1, LOOP1
		DJNZ R0, LOOP2
RET
END