;Program: Make a call using GSM
ORG 00H
	MOV TMOD,#20H	;timer 1 mode 2
	MOV TH1,#0FDH	;9600 baud
	MOV SCON,#50H	;enable UART
	SETB TR1	;enable timer 1
MAIN:
	MOV DPTR,#CALL_NUMBER	;make call (ATD number;)
NEXT:	CLR A
	MOVC A,@A+DPTR
	CJNE A,#0x0D,SEND_CALL
	MOV A,#0x0D
	ACALL SEND
	SJMP HERE
SEND_CALL:	ACALL SEND
	INC DPTR
	SJMP NEXT
HERE:	SJMP HERE

SEND:	;UART send
	CLR TI
    MOV SBUF,A
WAIT:	JNB TI,WAIT
RET

CALL_NUMBER: DB "ATD+918527136215;",0x0D
END